sudo: false
language: node_js
node_js:
  - "node"
branches:
  only:
  - main
install:
  - npm install
script:
  - npm run build
  - npm test

# Send coverage data to Coveralls
# after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
